ACTIVE_RUNTIME_MODULES = {
    "main": "Flask app factory and route wiring.",
    "runtime_config": "Environment loading, logging, and lazy external clients.",
    "memory_tree_core": "Weighted memory scaffold and active-context reinforcement.",
    "core_router": "Memory-first routing and sufficiency decisions for chat.",
    "memory_review_engine": "Compact metacognitive review layer for memory quality inspection.",
    "memory_core": "Persistent memory log access.",
    "codex": "Primary response generation and codex belief logging.",
    "reflection_core": "Reflection logging and reflective knowledge entries.",
    "dream_core": "Dream narrative generation for the active runtime.",
    "simulation_core": "Scenario simulation built from dream, reflection, and codex.",
    "knowledge_core": "Knowledge storage and retrieval.",
    "deepseek_api": "Topic explanation provider used by knowledge features.",
    "local_ollama_api": "Local Ollama transport for on-device LLM articulation/fallback.",
    "gemini_api": "Gemini transport for external LLM generation.",
    "openrouter_api": "External LLM transport with graceful fallback signaling.",
    "learning_firewall": "Input safety screening before response generation.",
    "tone_core": "Tone detection and response styling.",
    "brevity_core": "Response length shaping.",
    "retrieval_utils": "Shared relevance scoring and conflict heuristics.",
}

EXPERIMENTAL_MODULES = {
    "developer_core": "Protected patch workflow support; not loaded by the HTTP runtime.",
    "safe_evolution_core": "Patch integrity guardrails for experimental self-mod flows.",
    "oath_core": "Ethical patch validation helper for experimental tooling.",
    "raven_core": "Patch stability heuristic helper for experimental tooling.",
    "recursive_learning_engine": "Offline learning loop; not loaded by the Flask runtime.",
    "thought_chain_engine": "Experimental reasoning helper; not used by HTTP routes.",
    "auto_learn_batch": "Batch learning utility; intentionally decoupled from startup.",
    "knowledge_engine": "Offline topic learner helper; not part of runtime request flow.",
    "drift_core": "Support utility for personality drift tracking.",
    "emotion_core": "Emotion tagging helper used by experimental learning flows.",
    "personality_core": "Trait-state helper used by drift tooling.",
    "muhaimeen_heuristics": "Standalone heuristic helper, not wired into runtime routes.",
}
